name: Tests
on:
  push:
    branches: [ master, development ]
  workflow_dispatch:

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os-config: 
          - os: windows-latest
          - os: ubuntu-latest
            windowSystem: libx11-dev
          #- os: ubuntu-latest
            #windowSystem: libwayland-dev
    runs-on: ${{matrix.os-config.os}}
    name: Build and test on ${{ matrix.os-config.os }} ${{ matrix.os-config.windowSystem }}
    steps:
      - uses: actions/checkout@v4
      - name: Install packages and set up mock display
        if: matrix.os-config.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y libvorbis-dev libtheora-dev libwebp-dev libphysfs-dev libopusfile-dev libdumb1-dev libflac-dev libpulse-dev libgtk-3-dev pandoc libenet-dev pulseaudio libasound2-dev libopenal-dev \
            libgl1-mesa-dev libglu-dev libopenmpt-dev ${{ matrix.os-config.windowSystem }}
      - name: Install Conan
        uses: conan-io/setup-conan@v1
      - name: Build
        run: |
          mkdir build
          cd build
          cmake .. -DCMAKE_BUILD_TYPE=Release
          # --config Release is required for Windows; shouldn't do anything on Linux
          cmake --build . -j $(nproc) --config Release
      - name: Mock display (Ubuntu, xorg)
        if: matrix.os-config.os == 'ubuntu-latest' && matrix.os-config.windowSystem == 'libx11-dev'
        run: |
          export DEBIAN_FRONTEND=noninteractive DEBCONF_NONINTERACTIVE_SEEN=true
          echo "tzdata tzdata/Areas select Europe\ntzdata tzdata/Zones/Europe select Berlin" >> seed.txt
          sudo debconf-set-selections seed.txt
          sudo apt-get install -y xvfb xorg-dev libglu1-mesa libgl1-mesa-dev libxinerama1 libxcursor1 libgtk-3-0 matchbox-window-manager
          Xvfb :10 -ac -screen 0 1280x1024x24 & disown
          sleep 2 && DISPLAY=:10 matchbox-window-manager & disown
          echo "DISPLAY=:10" >> $GITHUB_ENV
      - name: Test (Everything but Windows)
        if: matrix.os-config.os != 'windows-latest'
        run: |
          cd build
          cmake --build . --target test
      - name: Test (Windows)
        if: matrix.os-config.os == 'windows-latest'
        run: |
          cd build
          cmake --build . --target tests --config Release
          .\bin\Release\tests.exe
  lint:
    runs-on: ubuntu-latest
    name: Run clang-tidy
    steps:
      - uses: actions/checkout@v4
      - name: Install deps
        run: |
          sudo apt-get update
          sudo apt-get install -y xvfb libvorbis-dev libtheora-dev libwebp-dev libphysfs-dev libopusfile-dev libdumb1-dev libflac-dev libpulse-dev libgtk-3-dev pandoc libenet-dev pulseaudio libasound2-dev libopenal-dev \
            libgl1-mesa-dev libglu-dev libopenmpt-dev libx11-dev
      - name: Install Conan
        uses: conan-io/setup-conan@v1
      - name: Check clang-tidy
        run: |
          mkdir build
          cd build
          cmake .. -DCMAKE_BUILD_TYPE=Release -DNYAA_LINT=ON -DLINT_WARNINGS_ARE_ERRORS=ON
          cmake --build . -j 2
